# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64

branches:
  only:
    - master
    - canary

image: Visual Studio 2019

install:
  - ps: Install-Product node 12 x64
  - set CI=true
  - yarn

build: off

matrix:
  fast_finish: true

shallow_clone: true

test_script:
  - node --version
  - yarn --version
  - yarn run test

on_success:
  - IF %APPVEYOR_REPO_BRANCH%==canary cp build\canary.ico build\icon.ico
  - yarn run dist
  - ps: Get-ChildItem .\dist\squirrel-windows\*.exe | % { Push-AppveyorArtifact $_.FullName }
